# Generated by Django 6.0.4 on 2026-06-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seguridad', '0002_bitacora_add_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('alergia', models.TextField(verbose_name='alergia')),
                ('condicion_preexistente', models.TextField(verbose_name='condicion preexistente')),
                ('factor_riesgo', models.TextField(verbose_name='factor de riesgo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='Seguridad.usuario')),
            ],
            options={
                'verbose_name': 'historia clinica',
                'verbose_name_plural': 'Historias clinicas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tipo_documento', models.CharField(choices=[('RESULTADO', 'Resultado'), ('FORMULARIOS', 'Formularios'), ('CONSENTIMIENTO', 'Consentimiento'), ('CERTIFICADO', 'Certificado')], max_length=20, verbose_name='tipo de documento')),
                ('encabezado', models.TextField(verbose_name='encabezado')),
                ('cuerpo', models.TextField(verbose_name='cuerpo')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Historias.historiaclinica', verbose_name='historia clinica')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('fecha_apertura', models.DateField(verbose_name='fecha de apertura')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('estado_caso', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20, verbose_name='estado del caso')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='prioridad')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='Historias.historiaclinica', verbose_name='historia clinica')),
            ],
            options={
                'verbose_name': 'caso',
                'verbose_name_plural': 'casos',
                'ordering': ('-fecha_apertura',),
            },
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tipo_antecedente', models.CharField(choices=[('HEREDOFAMILIARES', 'Heredofamiliares'), ('PERSONALES_NO_PATOLOGICOS', 'Personales no patologicos'), ('PERSONALES_PATOLOGICOS', 'Personales patologicos'), ('GINECO_OBSTETRICOS', 'Gineco obstetricos')], max_length=30, verbose_name='tipo de antecedente')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='Historias.historiaclinica', verbose_name='historia clinica')),
            ],
            options={
                'verbose_name': 'antecedente',
                'verbose_name_plural': 'antecedentes',
                'ordering': ('-fecha',),
            },
        ),
    ]
