export const colors = {
  bg: '#f9f9ff',
  surface: '#f9f9ff',
  surfaceDim: '#d5dae7',
  surfaceBright: '#f9f9ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f0f3ff',
  surfaceContainer: '#e9eefc',
  surfaceContainerHigh: '#e4e8f6',
  surfaceContainerHighest: '#dee2f0',
  inverseSurface: '#2b303b',
  inverseOnSurface: '#ecf0fe',
  onSurface: '#171c25',
  onSurfaceVariant: '#424752',
  hcText: '#171c25',
  outline: '#727784',
  outlineVariant: '#c2c6d4',
  surfaceTint: '#115cb9',
  primary: '#003f87',
  onPrimary: '#ffffff',
  primaryContainer: '#0056b3',
  onPrimaryContainer: '#bbd0ff',
  primaryFixed: '#d7e2ff',
  primaryFixedDim: '#acc7ff',
  onPrimaryFixed: '#001a40',
  onPrimaryFixedVariant: '#004491',
  inversePrimary: '#acc7ff',
  secondary: '#006a61',
  onSecondary: '#ffffff',
  secondaryContainer: '#86f2e4',
  onSecondaryContainer: '#006f66',
  secondaryFixed: '#89f5e7',
  secondaryFixedDim: '#6bd8cb',
  onSecondaryFixed: '#00201d',
  onSecondaryFixedVariant: '#005049',
  tertiary: '#2d18c7',
  onTertiary: '#ffffff',
  tertiaryContainer: '#473ddd',
  onTertiaryContainer: '#cdcbff',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
};

export const btnColors = {
  primary: { bg: colors.primary, text: colors.onPrimary, hover: colors.onPrimaryFixedVariant },
  secondary: { bg: colors.surfaceContainerLow, text: colors.secondary, hover: colors.surfaceContainerHigh },
  tertiary: { bg: 'transparent', text: colors.onSurfaceVariant, hover: colors.surfaceContainerLow },
  danger: { bg: colors.error, text: colors.onError, hover: colors.onErrorContainer },
  success: { bg: colors.secondary, text: colors.onSecondary, hover: colors.secondaryFixedDim },
};

export const cardColors = {
  bg: colors.surfaceContainerLowest,
  border: colors.outlineVariant,
  muted: colors.onSurfaceVariant,
};

export const radius = {
  sm: 4,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
};
