# Generated by Django 6.0.5 on 2026-05-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agendas', '0002_rename_activo_servicio_es_activo'),
        ('Seguridad', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('GENERAL', 'Estadístico General de Consultas'), ('ESPECIALIDAD', 'Consultas por Tipo de Atención')], default='GENERAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seguridad.usuario')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agendas.servicio')),
            ],
        ),
    ]
