# Generated by Django 6.0.4 on 2026-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
