# Generated by Django 6.0.5 on 2026-05-13 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIDA', 'No asistida')], default='AGENDADA', max_length=16)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('remitente_id', models.IntegerField()),
                ('destinatario', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=10)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('presion_arterial', models.CharField(max_length=32)),
                ('frecuencia_cardiaca', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='Agendas.cita')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nivel_socioeconomico', models.CharField(blank=True, max_length=120)),
                ('descripcion_vivienda', models.TextField(blank=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_consultas', to='Agendas.cita')),
                ('historia_clinica_id', models.IntegerField()),
                ('servicios', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_servicios', to='Agendas.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaPsicologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas_evolucion', models.TextField(blank=True)),
                ('estado_humor', models.CharField(blank=True, max_length=120)),
                ('nivel_ansiedad', models.PositiveIntegerField(default=0)),
                ('nivel_autoestima', models.PositiveIntegerField(default=0)),
                ('diagnostico', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_consultas', to='Agendas.cita')),
                ('historia_clinica_id', models.IntegerField()),
                ('servicios', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_servicios', to='Agendas.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaOdontologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('odontograma', models.TextField()),
                ('procedimientos', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_consultas', to='Agendas.cita')),
                ('historia_clinica_id', models.IntegerField()),
                ('servicios', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_servicios', to='Agendas.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='citas', to='Agendas.servicio'),
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anamnesis', models.TextField()),
                ('tratamiento', models.TextField()),
                ('diagnostico', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_consultas', to='Agendas.cita')),
                ('historia_clinica_id', models.IntegerField()),
                ('servicios', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_servicios', to='Agendas.servicio')),
                ('signos_vitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendas.signosvitales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('usuario_id', 'fecha_hora')},
        ),
    ]
