# Generated by Django 6.0.5 on 2026-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='activo',
            new_name='es_activo',
        ),
    ]
