# Generated by Django 6.0.5 on 2026-06-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendas', '0003_seed_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='profesional_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
