# Generated by Django 6.0.5 on 2026-06-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agendas', '0004_cita_profesional_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
    ]
