# Generated by Django 6.0.5 on 2026-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendas', '0005_eliminar_unique_together_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIDA', 'No asistida'), ('REAGENDADA', 'Reagendada')], default='AGENDADA', max_length=16),
        ),
    ]
