# Generated by Django 6.0.4 on 2026-05-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_precargar_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='tipo_accion',
            field=models.CharField(choices=[('registro', 'Registro'), ('inicio_sesion', 'Inicio de sesión'), ('inicio_sesion_fallido', 'Inicio de sesión fallido'), ('refresco_token', 'Refresco de token'), ('acceso', 'Acceso'), ('cambio_rol', 'Cambio de rol')], max_length=50),
        ),
    ]
