# Generated by Django 6.0.5 on 2026-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('creacion', 'Creación'), ('confirmacion', 'Confirmación'), ('reagendamiento', 'Reagendamiento'), ('cancelacion', 'Cancelación'), ('derivacion', 'Derivación'), ('atencion', 'Atención registrada'), ('actualizacion_historia', 'Actualización de historia clínica')], max_length=32),
        ),
    ]
